import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Appbar from "@repo/ui/Appbar";
import Bg from "@repo/ui/Bg";
import { SignIn,SignOut,SignUp } from "./components/Signin";
import Providers from "./providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
        <Bg>
        <Appbar title="Zapp" buttons={{SignIn,SignOut,SignUp}}  isAuth={false}/>
        {children}
        </Bg>
        </Providers>
        
      </body>
    </html>
  );
}
